package cn.ling.yu.permission

const val PERMISSION_ALL_GRANT_RESULTS="sdk_permission_all_grant_results"
const val PERMISSION_SOME_DENIED_RESULTS="sdk_permission_some_denied_results"
const val PERMISSION_AGAIN_NOT_REMIND="sdk_permission_again_not_remind"
const val PERMISSION_ALL_DENIED_RESULTS="sdk_permission_all_denied_results"

const val PERMISSION_REQUEST_OBJ="sdk_permission_result_obj"
const val PERMISSION_ASK_LIST_RETURN="sdk_permission_ask_list_return"
const val PERMISSION_REMIND_DENIED_RETURN="sdk_permission_remind_denied_return"
const val PERMISSION_REQUEST_TYPE="sdk_permission_request_type"

const val PERMISSION_REQUEST="sdk_permission_request"
const val PERMISSION_ASK_REQUEST="sdk_permission_ask_request"
const val PERMISSION_ALL_DENIED_REQUEST="sdk_permission_denied_request"